# Generated by Django 2.0.5 on 2018-05-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180527_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock_code',
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='trade.Stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.IntegerField(unique=True),
        ),
    ]
