# Generated by Django 2.0.5 on 2018-05-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20180527_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
