# Generated by Django 2.0.3 on 2018-05-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_subjects',
            fields=[
                ('subject_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('accounting_name', models.CharField(max_length=50)),
                ('subject_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Accounting_subjects_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ID', models.CharField(max_length=50)),
                ('accounting_name', models.CharField(max_length=50)),
                ('company_ID', models.CharField(max_length=100)),
                ('subject_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('subject_ID', models.CharField(max_length=100)),
                ('Dr_Cr', models.CharField(max_length=50)),
                ('money', models.FloatField()),
                ('activity_type', models.CharField(blank=True, max_length=50)),
                ('abstract', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('company_ID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
