"""
Django settings for exchange project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%6k_ja%(@lvo$g2*cxy=s(ivg%l7-ild7g_q!+gn60*7@g6fdi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#bushu
#ALLOWED_HOSTS = ['http://hahayahaha.pythonanywhere.com/']
ALLOWED_HOSTS = []
AUTHENTICATION_BACKENDS = (
    'user.views.CustomBackend',

)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exchange.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exchange.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', #修改成mysql
        'NAME': 'exclogin',  #需要连接的数据库的名字
        'USER': 'root',  #安装mysql时的用户名
        'PASSWORD': '707398', #安装mysql时的密码
        'HOST': '127.0.0.1', #本地
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql', #修改成mysql
#        'NAME': 'exc',  #需要连接的数据库的名字
#        'USER': 'hahayahaha',  #安装mysql时的用户名
#        'PASSWORD': '123456exc', #安装mysql时的密码
#        'HOST': 'hahayahaha.mysql.pythonanywhere-services.com', #本地
#    }
#}



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# 语言改为中文
LANGUAGE_CODE = 'zh-hans'

# 时区改为上海
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#bushu
#STATIC_ROOT=os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'
AUTH_USER_MODEL = 'user.UserProfile'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)



# 163 SMTP 配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # 新浪 smtp 服务器地址
EMAIL_PORT = 25  # 端口号
EMAIL_USE_TLS = True 
#发送邮件的邮箱
EMAIL_HOST_USER = 'exchange_nju@163.com'

SERVER_EMAIL = 'exchange_nju@163.com'
#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'nju123456'

#收件人看到的发件人
EMAIL_FROM = 'exchange_nju@163.com'

